apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.aspnetcoreEnvironment }}"
  ASPNETCORE_URLS: "{{ .Values.config.aspnetcoreUrls }}"
  TZ: America/Argentina/Buenos_Aires